{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "zb-spring-template-chart.serviceAccountName" . }}
  labels:
{{ include "zb-spring-template-chart.labels" . | indent 4 }}
{{- end -}}
