apiVersion: v1
kind: Namespace
metadata:
  name: zb-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zb-config-sa
  namespace: zb-config
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: zb-config-role
  namespace: zb-config
rules:
  - apiGroups:
      - "extensions"
    resources:
      - podsecuritypolicies
    resourceNames:
      - pks-restricted # for psp security
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp-exmaple-role-binding
  namespace: zb-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zb-config
subjects:
  - kind: ServiceAccount
    name: zb-config-sa
    namespace: zb-config
