{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "zb-config-server-chart.serviceAccountName" . }}
  labels:
{{ include "zb-config-server-chart.labels" . | indent 4 }}
{{- end -}}
