apiVersion: v1
kind: Service
metadata:
  name: {{ include "zb-java-ms-example-chart.fullname" . }}
  labels:
{{ include "zb-java-ms-example-chart.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.healthPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "zb-java-ms-example-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
